### ISSUE TITLE
Receive error when using cif file containing isotropic atomic displacement parameters

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/xfab#6]
I receive the following error when I try to run PolyXSim with a certain .cif structure file specified:

```
Traceback (most recent call last):
  File "/home/kuc84153/.pyenv/versions/ImageD11_venv/bin/PolyXSim.py", line 18, in <module>
    gopolyxsim.run(options)
  File "/home/kuc84153/.pyenv/versions/2.7.16/envs/ImageD11_venv/lib/python2.7/site-packages/polyxsim/gopolyxsim.py", line 106, in run
    xtal_structure = reflections.open_structure(myinput.param,phase)
  File "/home/kuc84153/.pyenv/versions/2.7.16/envs/ImageD11_venv/lib/python2.7/site-packages/polyxsim/reflections.py", line 35, in open_structure
    struct.CIFread(ciffile=file,cifblkname=datablock)
  File "/home/kuc84153/.pyenv/versions/2.7.16/envs/ImageD11_venv/lib/python2.7/site-packages/xfab/structure.py", line 401, in CIFread
    adp = adp, occ=occ , symmulti=multi)
UnboundLocalError: local variable 'adp' referenced before assignment
```

I believe this is because, in the CifRead function inside **structure.py**, the adp variable is only populated if the adp_type is one of None, 'Uiso' or 'Uani', but my input .cif has 'Biso' for _atom_site_adp_type instead:
```
if adp_type == None:
    adp = 0.0
elif adp_type == 'Uiso':
    adp = self.remove_esd(cifblk['_atom_site_U_iso_or_equiv'][i])
elif adp_type == 'Uani':
    anisonumber = cifblk['_atom_site_aniso_label'].index(label)
    adp = [ self.remove_esd(cifblk['_atom_site_aniso_U_11'][anisonumber]),
        self.remove_esd(cifblk['_atom_site_aniso_U_22'][anisonumber]),
        self.remove_esd(cifblk['_atom_site_aniso_U_33'][anisonumber]),
        self.remove_esd(cifblk['_atom_site_aniso_U_23'][anisonumber]),
        self.remove_esd(cifblk['_atom_site_aniso_U_13'][anisonumber]),
        self.remove_esd(cifblk['_atom_site_aniso_U_12'][anisonumber])]
self.atomlist.add_atom(label=label, atomtype=atomtype,
                                   pos = [x, y, z], adp_type= adp_type, 
                                   adp = adp, occ=occ , symmulti=multi)
```

I have attached the input .cif file in case there's anything wrong with it:

```
#------------------------------------------------------------------------------
#$Date: 2016-07-15 05:33:48 +0300 (Fri, 15 Jul 2016) $
#$Revision: 184466 $
#$URL: file:///home/coder/svn-repositories/cod/cif/1/54/36/1543667.cif $
#------------------------------------------------------------------------------
#
# This file is available in the Crystallography Open Database (COD),
# http://www.crystallography.net/
#
# All data on this site have been placed in the public domain by the
# contributors.
#
data_1543667
loop_
_publ_author_name
'Oila, Adrian'
'Bull, Steve'
_publ_contact_author
;
 Adrian Oila
 Newcastle University
 Newcastle upon Tyne
 NE17RU
 United Kingdom
;
_publ_contact_author_email       Adrian.Oila@newcastle.ac.uk
_publ_section_title
;
 Atomistic simulation of Fe-C austenite
;
_journal_issue                   2
_journal_name_full               'Computational Materials Science'
_journal_page_first              235
_journal_page_last               239
_journal_paper_doi               10.1016/j.commatsci.2008.09.013
_journal_volume                  45
_journal_year                    2009
_chemical_formula_analytical     'C9 Fe125'
_chemical_formula_iupac          'C9 Fe125'
_chemical_formula_moiety         'C9 Fe125'
_chemical_formula_structural     'C9 Fe125'
_chemical_formula_sum            'C9 Fe125'
_space_group_IT_number           225
_symmetry_cell_setting           cubic
_symmetry_Int_Tables_number      225
_symmetry_space_group_name_Hall  '-F 4 2 3'
_symmetry_space_group_name_H-M   'F m -3 m'
_cell_angle_alpha                90
_cell_angle_beta                 90
_cell_angle_gamma                90
_cell_formula_units_Z            12
_cell_length_a                   18.48730
_cell_length_b                   18.48730
_cell_length_c                   18.48730
_cell_volume                     6318.594
_exptl_crystal_density_diffrn    7.452471
_cod_data_source_file            Fe125C9.cif
_cod_data_source_block           global
_cod_original_cell_volume        6318.609362
_cod_database_code               1543667
loop_
_symmetry_equiv_pos_as_xyz
'x, y, z'
'-x, -y, -z'
'-x, -y, z'
'x, y, -z'
'-x, y, -z'
'x, -y, z'
'x, -y, -z'
'-x, y, z'
'z, x, y'
'-z, -x, -y'
'z, -x, -y'
'-z, x, y'
'-z, -x, y'
'z, x, -y'
'-z, x, -y'
'z, -x, y'
'y, z, x'
'-y, -z, -x'
'-y, z, -x'
'y, -z, x'
'y, -z, -x'
'-y, z, x'
'-y, -z, x'
'y, z, -x'
'y, x, -z'
'-y, -x, z'
'-y, -x, -z'
'y, x, z'
'y, -x, z'
'-y, x, -z'
'-y, x, z'
'y, -x, -z'
'x, z, -y'
'-x, -z, y'
'-x, z, y'
'x, -z, -y'
'-x, -z, -y'
'x, z, y'
'x, -z, y'
'-x, z, -y'
'z, y, -x'
'-z, -y, x'
'z, -y, x'
'-z, y, -x'
'-z, y, x'
'z, -y, -x'
'-z, -y, -x'
'z, y, x'
'x, y+1/2, z+1/2'
'-x, -y+1/2, -z+1/2'
'-x, -y+1/2, z+1/2'
'x, y+1/2, -z+1/2'
'-x, y+1/2, -z+1/2'
'x, -y+1/2, z+1/2'
'x, -y+1/2, -z+1/2'
'-x, y+1/2, z+1/2'
'z, x+1/2, y+1/2'
'-z, -x+1/2, -y+1/2'
'z, -x+1/2, -y+1/2'
'-z, x+1/2, y+1/2'
'-z, -x+1/2, y+1/2'
'z, x+1/2, -y+1/2'
'-z, x+1/2, -y+1/2'
'z, -x+1/2, y+1/2'
'y, z+1/2, x+1/2'
'-y, -z+1/2, -x+1/2'
'-y, z+1/2, -x+1/2'
'y, -z+1/2, x+1/2'
'y, -z+1/2, -x+1/2'
'-y, z+1/2, x+1/2'
'-y, -z+1/2, x+1/2'
'y, z+1/2, -x+1/2'
'y, x+1/2, -z+1/2'
'-y, -x+1/2, z+1/2'
'-y, -x+1/2, -z+1/2'
'y, x+1/2, z+1/2'
'y, -x+1/2, z+1/2'
'-y, x+1/2, -z+1/2'
'-y, x+1/2, z+1/2'
'y, -x+1/2, -z+1/2'
'x, z+1/2, -y+1/2'
'-x, -z+1/2, y+1/2'
'-x, z+1/2, y+1/2'
'x, -z+1/2, -y+1/2'
'-x, -z+1/2, -y+1/2'
'x, z+1/2, y+1/2'
'x, -z+1/2, y+1/2'
'-x, z+1/2, -y+1/2'
'z, y+1/2, -x+1/2'
'-z, -y+1/2, x+1/2'
'z, -y+1/2, x+1/2'
'-z, y+1/2, -x+1/2'
'-z, y+1/2, x+1/2'
'z, -y+1/2, -x+1/2'
'-z, -y+1/2, -x+1/2'
'z, y+1/2, x+1/2'
'x+1/2, y, z+1/2'
'-x+1/2, -y, -z+1/2'
'-x+1/2, -y, z+1/2'
'x+1/2, y, -z+1/2'
'-x+1/2, y, -z+1/2'
'x+1/2, -y, z+1/2'
'x+1/2, -y, -z+1/2'
'-x+1/2, y, z+1/2'
'z+1/2, x, y+1/2'
'-z+1/2, -x, -y+1/2'
'z+1/2, -x, -y+1/2'
'-z+1/2, x, y+1/2'
'-z+1/2, -x, y+1/2'
'z+1/2, x, -y+1/2'
'-z+1/2, x, -y+1/2'
'z+1/2, -x, y+1/2'
'y+1/2, z, x+1/2'
'-y+1/2, -z, -x+1/2'
'-y+1/2, z, -x+1/2'
'y+1/2, -z, x+1/2'
'y+1/2, -z, -x+1/2'
'-y+1/2, z, x+1/2'
'-y+1/2, -z, x+1/2'
'y+1/2, z, -x+1/2'
'y+1/2, x, -z+1/2'
'-y+1/2, -x, z+1/2'
'-y+1/2, -x, -z+1/2'
'y+1/2, x, z+1/2'
'y+1/2, -x, z+1/2'
'-y+1/2, x, -z+1/2'
'-y+1/2, x, z+1/2'
'y+1/2, -x, -z+1/2'
'x+1/2, z, -y+1/2'
'-x+1/2, -z, y+1/2'
'-x+1/2, z, y+1/2'
'x+1/2, -z, -y+1/2'
'-x+1/2, -z, -y+1/2'
'x+1/2, z, y+1/2'
'x+1/2, -z, y+1/2'
'-x+1/2, z, -y+1/2'
'z+1/2, y, -x+1/2'
'-z+1/2, -y, x+1/2'
'z+1/2, -y, x+1/2'
'-z+1/2, y, -x+1/2'
'-z+1/2, y, x+1/2'
'z+1/2, -y, -x+1/2'
'-z+1/2, -y, -x+1/2'
'z+1/2, y, x+1/2'
'x+1/2, y+1/2, z'
'-x+1/2, -y+1/2, -z'
'-x+1/2, -y+1/2, z'
'x+1/2, y+1/2, -z'
'-x+1/2, y+1/2, -z'
'x+1/2, -y+1/2, z'
'x+1/2, -y+1/2, -z'
'-x+1/2, y+1/2, z'
'z+1/2, x+1/2, y'
'-z+1/2, -x+1/2, -y'
'z+1/2, -x+1/2, -y'
'-z+1/2, x+1/2, y'
'-z+1/2, -x+1/2, y'
'z+1/2, x+1/2, -y'
'-z+1/2, x+1/2, -y'
'z+1/2, -x+1/2, y'
'y+1/2, z+1/2, x'
'-y+1/2, -z+1/2, -x'
'-y+1/2, z+1/2, -x'
'y+1/2, -z+1/2, x'
'y+1/2, -z+1/2, -x'
'-y+1/2, z+1/2, x'
'-y+1/2, -z+1/2, x'
'y+1/2, z+1/2, -x'
'y+1/2, x+1/2, -z'
'-y+1/2, -x+1/2, z'
'-y+1/2, -x+1/2, -z'
'y+1/2, x+1/2, z'
'y+1/2, -x+1/2, z'
'-y+1/2, x+1/2, -z'
'-y+1/2, x+1/2, z'
'y+1/2, -x+1/2, -z'
'x+1/2, z+1/2, -y'
'-x+1/2, -z+1/2, y'
'-x+1/2, z+1/2, y'
'x+1/2, -z+1/2, -y'
'-x+1/2, -z+1/2, -y'
'x+1/2, z+1/2, y'
'x+1/2, -z+1/2, y'
'-x+1/2, z+1/2, -y'
'z+1/2, y+1/2, -x'
'-z+1/2, -y+1/2, x'
'z+1/2, -y+1/2, x'
'-z+1/2, y+1/2, -x'
'-z+1/2, y+1/2, x'
'z+1/2, -y+1/2, -x'
'-z+1/2, -y+1/2, -x'
'z+1/2, y+1/2, x'
loop_
_atom_site_label
_atom_site_occupancy
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_adp_type
_atom_site_B_iso_or_equiv
_atom_site_type_symbol
_atom_type_symbol
Fe 1.0 0.000000 0.000000 0.000000 Biso 1.000000 Fe Fe
Fe 1.0 0.000000 0.000000 0.201800 Biso 1.000000 Fe Fe
Fe 1.0 0.000000 0.000000 0.403300 Biso 1.000000 Fe Fe
Fe 1.0 0.000000 0.200800 0.200800 Biso 1.000000 Fe Fe
Fe 1.0 0.000000 0.400300 0.400300 Biso 1.000000 Fe Fe
Fe 1.0 0.000000 0.199900 0.399900 Biso 1.000000 Fe Fe
Fe 1.0 0.200400 0.200400 0.200400 Biso 1.000000 Fe Fe
Fe 1.0 0.399400 0.399400 0.399400 Biso 1.000000 Fe Fe
Fe 1.0 0.200100 0.200100 0.399800 Biso 1.000000 Fe Fe
Fe 1.0 0.196400 0.400200 0.400200 Biso 1.000000 Fe Fe
C 1.0 0.500000 0.500000 0.500000 Biso 1.000000 C C
C 1.0 0.101700 0.101700 0.101700 Biso 1.000000 C C
```

**Comment by jonwright** [comment]
Looks like a bug to me, thanks for figuring this out! 
It could allow Biso/Bani and convert it to U using "B = 8 pi^2 U". 
I guess it was always using cifs with U until now. 
Do you want to try to fix it?

**Comment by jadball** [comment]
Thanks for picking this up!
I'll have a go at fixing it.
My idea is to detect Biso/Bani, convert them to U, then change the adp_type to Uiso/Uani afterwards so that the rest of the code works with it.

**Comment by jadball** [comment]
I've created the pull request now - hope it looks okay! #7

**Comment by jadball** [comment]
Closing as merged.
